version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@123
      MYSQL_DATABASE: myblog
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      springboot-mysql-net:

  springboot-rest-service:
    container_name: springboot-rest-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      springboot-mysql-net:
    restart: on-failure

volumes:
  mysql_data:

networks:
  springboot-mysql-net: